version: "3"
services: 
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
     - "3000:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes: 
      - ./jiro-stamp-rally:/app
    tty: true
  mysql:
    image: mysql:8.0.27
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
  workspace:
    build:
      context: .
      dockerfile: ./jiro-stamp-rally/docker/workspace/Dockerfile
    tty: true
    volumes:
      - ./:/workspace
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    links:
      - mysql

  
volumes:
 mysql-data:
  driver: local

