version: "3"
services: 
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
     - "3000:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: jiro-stamp-rally
      DB_USER: user
      DB_PASSWORD: password
    volumes: 
      - ./jiro-stamp-rally:/app
    tty: true
  mysql:
    image: mysql:8.0.27
    ports:
      - 3306:3306
    environment:
      TZ: 
      MYSQL_DATABASE: jiro-stamp-rally
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
  
volumes:
 mysql-data:
  driver: local

